# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vss_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vss_data.proto',
  package='proto_struct',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0evss_data.proto\x12\x0cproto_struct\"D\n\x07VssData\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x10\n\x08\x64\x61ta_int\x18\x02 \x01(\x05\x12\x12\n\ndata_float\x18\x03 \x01(\x02\x62\x06proto3')
)




_VSSDATA = _descriptor.Descriptor(
  name='VssData',
  full_name='proto_struct.VssData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='proto_struct.VssData.description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_int', full_name='proto_struct.VssData.data_int', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_float', full_name='proto_struct.VssData.data_float', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['VssData'] = _VSSDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VssData = _reflection.GeneratedProtocolMessageType('VssData', (_message.Message,), dict(
  DESCRIPTOR = _VSSDATA,
  __module__ = 'vss_data_pb2'
  # @@protoc_insertion_point(class_scope:proto_struct.VssData)
  ))
_sym_db.RegisterMessage(VssData)


# @@protoc_insertion_point(module_scope)
